[tool.poetry]
name = "mcpy"
version = "0.1.0"
description = ""
authors = ["Kalel L. Martinho <kalelmartinho@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyglet = "^2.0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
